# Generated by Django 3.2.13 on 2022-05-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=30)),
                ('user_type', models.CharField(max_length=4)),
            ],
        ),
    ]
